# Generated by Django 6.1.1 on 2026-09-20 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('delivery_address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=20)),
                ('payment_timing', models.CharField(choices=[('on_delivery', 'Pay on delivery'), ('advance', 'Advance payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('subtotal', models.PositiveIntegerField()),
                ('delivery_charge', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('line_total', models.PositiveIntegerField()),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.order')),
            ],
        ),
    ]
